name: moon_chick
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../mainchick-mobile/packages/core
  cage:
    path: ../mainchick-mobile/packages/cage
  analysis:
    path: ../mainchick-mobile/packages/analysis
  feed:
    path: ../mainchick-mobile/packages/feed
  history:
    path: ../mainchick-mobile/packages/history
  profile:
    path: ../mainchick-mobile/packages/profile
  chatbot:
    path: ../mainchick-mobile/packages/chatbot

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  http: ^1.0.0
  provider: ^6.0.5
  google_fonts: ^5.0.0
  firebase_core: ^2.13.0
  dcdg: ^4.1.0
  google_generative_ai: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icons/launcher.png'

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/solution/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
          weight: 400
    - family: Rubik-Light
      fonts:
        - asset: fonts/Rubik-Light.ttf
          weight: 300
    - family: Rubik-Medium
      fonts:
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
    - family: Rubik-SemiBold
      fonts:
        - asset: fonts/Rubik-SemiBold.ttf
          weight: 600
    - family: Rubik-Bold
      fonts:
        - asset: fonts/Rubik-Bold.ttf
          weight: 700
    - family: Rubik-ExtraBold
      fonts:
        - asset: fonts/Rubik-ExtraBold.ttf
          weight: 800
