// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXLpacmZrZr_seGT_f6n1-IvqGK8IBTQ4',
    appId: '1:172329059556:android:7f1046aec165921c0cd8f1',
    messagingSenderId: '172329059556',
    projectId: 'cimerangfarm-421db',
    databaseURL: 'https://cimerangfarm-421db.firebaseio.com',
    storageBucket: 'cimerangfarm-421db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClHiJv2NAvIc3WqmApfPZPoBdjHYDfV-M',
    appId: '1:172329059556:ios:1b4fe01c405eb6440cd8f1',
    messagingSenderId: '172329059556',
    projectId: 'cimerangfarm-421db',
    databaseURL: 'https://cimerangfarm-421db.firebaseio.com',
    storageBucket: 'cimerangfarm-421db.appspot.com',
    androidClientId:
        '172329059556-q2ql7vlm2qfqv6c5qdg47k43afaj7v8p.apps.googleusercontent.com',
    iosClientId:
        '172329059556-vs2r4qeorrq41sd4trln9srl9gtv748o.apps.googleusercontent.com',
    iosBundleId: 'id.ac.unikom.codelabs.moonchick',
  );
}
