name: core
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cage:
    path: ../cage
  analysis:
    path: ../analysis
  feed:
    path: ../feed
  history:
    path: ../history
  profile:
    path: ../profile
  chatbot:
    path: ../chatbot
  notification:
    path: ../notification

  equatable: ^2.0.5
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
