name: chatbot
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_svg: ^1.1.6
  http: ^1.0.0
  image_picker: ^0.8.6+4
  image: ^3.0.2
  provider: ^6.0.5
  google_generative_ai: ^0.3.0
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
